name: PacketLogger
version: 2.0.0
main: mmm545\PacketLogger\PacketLogger
api: 4.0.0
author: mmm545
src-namespace-prefix: mmm545\PacketLogger
commands:
  pklog:
    description: Dumps all the log contents
    permission: pklogger.log
  pkclear:
    description: Clears the log file contents
    permission: pklogger.clear
  pkreload:
    description: Reloads config
    permission: pklogger.reload

permissions:
  pklogger.log:
    description: Gives permission to dump all the log contents
  pklogger.clear:
    description: Gives permission to clear the log file
  pklogger.reload:
    description: Gives permission to reload the config