---
# Allow sent packets to be logged
# values: true/false
log_sent_packets: true

# Allow received packets to be logged
# values: true/false
log_received_packets: true

# Block certain types of packets from being logged
# values: true/false
block_packets: false

# Here you will put the name of packets you want to block from being logged
# Type the name correctly
blocked_packets: []
...