---
# Allow sent packets to be logged
# values: true/false
log_sent_packets: true

# Allow received packets to be logged
# values: true/false
log_received_packets: true

# Mode can be either "blacklist" or "whitelist"
# blacklist will log all the packets except the ones specified below
# whitelist will only log the packets specified below
# Default is blacklist
mode: blacklist

# List of blacklisted/whitelisted packets
packets: []
...